ROOT_PATH 		:= /root
ATHRILL_ROOT	:= $(ROOT_PATH)/athrill-target-v850e2m
BUILD_PATH		:= $(ROOT_PATH)/workspace/build
CPU_CONFIG_PATH	:= $(ATHRILL_ROOT)/src/cpu/config
$(info ROOT_PATH=$(ROOT_PATH))
$(info ATHRILL_ROOT=$(ATHRILL_ROOT))
$(info BUILD_PATH=$(BUILD_PATH))
$(info CPU_CONFIG_PATH=$(CPU_CONFIG_PATH))

include $(BUILD_PATH)/Makefile.common
